package com.example.nacho.proyectosdm.persistence.esquemas;

import android.provider.BaseColumns;

/**
 * Created by Laura Mambo on 18/10/2017.
 */

//Variables estaticas
public class Esquemas {

    // Nombre de la tabla valoratios y sus columnas
    public static final String TABLA_USUARIO = "USUARIOS";
    public static final String ID = "id";
    public static final String NOMBRE = "nombre";
    public static final String CONTRASEÑA = "contraseña";
    public static final String EMAIL = "email";

    public static final String TABLA_COMIDA = "COMIDAS";
    public static final String TABLA_MENSAJES = "MENSAJES";
    public static final String TABLA_VENDIDOS = "VENDIDOS";

    //Scrip para crear la base datos

  //  public static final String CREAR_TABLA_USUARIO = "CREATE TABLE" + TABLA_USUARIO + " ( " + ID + " INTEGER, " + NOMBRE + " TEXT," + NOMBRE + " TEXT," + CONTRASEÑA + " TEXT )";

//## POR EL MOMENTO VAMOS A USAR ESTA HASTA QUE HAYA MAS PARAMETROS.

    public static final String CREAR_TABLA_USUARIO =
            "CREATE TABLE " + TABLA_USUARIO + " ( " +
                    ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
                    NOMBRE + " TEXT NOT NULL, " +
                    CONTRASEÑA + " TEXT  NOT NULL, " +
                    EMAIL + "TEXT NOT NULL, " +
                    "CONSTRAINT nombre_unique UNIQUE (" + NOMBRE + ")," +
                    "CHECK ( length(" + NOMBRE + ") > 0), " +
                    "CHECK ( length(" + CONTRASEÑA + ") > 0)"+
                    ");";



    /**public static final String CREAR_TABLA_USUARIO ="CREATE TABLE " + TABLA_USUARIO + " ( " +
            ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
            EMAIL + " TEXT NOT NULL, " +
            NOMBRE + " TEXT NOT NULL, " +
            "CIUDAD VARCHAR(255) NOT NULL, "+
            "FECHA_ALTA TIMESTAMP,"+
            CONTRASEÑA + " TEXT  NOT NULL, " +
            "ACTIVO BOOLEAN, "+
            "CONSTRAINT nombre_unique UNIQUE (" + NOMBRE + ")," +
            "CHECK ( length(" + NOMBRE + ") > 0), " +
            "CHECK ( length(" + CONTRASEÑA + ") > 0)"+
            ");";  */


    //public static final String CREAR_TABLA_USUARIO = "CREATE MEMORY TABLE PUBLIC.USUARIO(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,NOMBRE VARCHAR(255) NOT NULL,CIUDAD VARCHAR(255) NOT NULL,FECHA_ALTA TIMESTAMP, PASSWORD VARCHAR(255) NOT NULL, ACTIVO BOOLEAN) ALTER TABLE PUBLIC.USUARIO ALTER COLUMN ID RESTART WITH 1";
    public static final String CREAR_TABLA_COMIDA = "CREATE TABLE "+TABLA_COMIDA+" (ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,CONSTRAINT CORREO_USUARIO FOREIGN KEY(CORREO) REFERENCES PUBLIC.USUARIO(CORREO),NOMBRE VARCHAR(255) NOT NULL,RACIONES INTEGER,PRECIO DOUBLE,DESCRIPCION VARCHAR(255),SALADO BOOLEAN,DULCE BOOLEAN,VEGETARIANO BOOLEAN,CELIACO BOOLEAN,CATEGORIA ENUM('desayuno','comida','merienda','cena'))";
    public static final String CREAR_TABLA_MENSAJES = "CREATE TABLE "+TABLA_MENSAJES+" (CONSTRAINT CORREO_EMISOR FOREIGN KEY(CORREO) REFERENCES PUBLIC.USUARIO(CORREO), CONSTRAINT CORREO_RECEPTOR FOREIGN KEY(CORREO) REFERENCES PUBLIC.USUARIO(CORREO), MENSAJE VARCHAR(255) NOT NULL, FECHA TIMESTAMP)";
    public static final String CREAR_TABLA_VENDIDOS = "CREATE TABLE "+TABLA_VENDIDOS+" (CONSTRAINT ID_COMIDA FOREIGN KEY(ID) REFERENCES PUBLIC.COMIDA(ID), CONSTRAINT CORREO_COMPRADOR FOREIGN KEY(CORREO) REFERENCES PUBLIC.USUARIO(CORREO), FECHA_VENTA FECHA TIMESTAMP, VALORACION INTEGER)";

    public static final String SCRIPT_CREACION=
            "INSERT INTO USUARIOS VALUES('jon@gmail.com','Jon','Gijón','2017-10-16 14:00:00.000000', 'password', true)\n" +
            "INSERT INTO USUARIOS VALUES('sansa@gmail.com','Sansa','Oviedo','2017-10-16 14:00:00.000000', 'password', true)\n" +
            "INSERT INTO USUARIOS VALUES('bran@gmail.com','Bran','Gijón','2017-10-16 14:00:00.000000', 'password', true)\n" +
            "INSERT INTO USUARIOS VALUES('aria@gmail.com','Aria','Oviedo','2017-10-16 14:00:00.000000', 'password', true)"+
            "INSERT INTO COMIDAS VALUES(1, 'sansa@gmail.com', 'Macarrones boloñesa', 5, 5.95, 'macarrones como los que hacia mi abuela', true, false, false,true,'comida')\n"+
            "INSERT INTO COMIDAS VALUES(2, 'jon@gmail.com', 'Pizza margarita', 4, 3.15, 'pizza traicional con queso y tomate', true, false, true,false,'comida')\n"+
            "INSERT INTO COMIDAS VALUES(3, 'aria@gmail.com', 'Paella', 4, 5.95, 'pizza traicional con queso y tomate', true, false, false,false,'comida')\n"+
            "INSERT INTO COMIDAS VALUES(4, 'bran@gmail.com', 'Pastel', 8, 1.95, 'Pastel de chocolate rico rico', false, true, true,false,'Merienda')\n"+
            "INSERT INTO COMIDAS VALUES(5, 'jon@gmail.com', 'Macedonia', 3, 1.00, 'Manzana, naranja, piña, plátano y pera', false, true, true,true,'Merienda')\n"+
            "INSERT INTO COMIDAS VALUES(6, 'sansa@gmail.com', 'Lentejas', 8, 2.15, '', true, false, true,false,'comida')\n"+
            "INSERT INTO COMIDAS VALUES(7, 'bran@gmail.com', 'Rosquillas', 4, 1.20, '', false, true, false,false,'Desayuno')\n"+
            "INSERT INTO COMIDAS VALUES(8, 'aria@gmail.com', 'Tortilla de patata', 6, , '', true, false, false,false,'Merienda')"+
            "INSERT INTO MENSAJES VALUES('sansa@gmail.com', 'jon@gmail.com', 'La foto de esos macarrones de cuando es?', '2017-11-15 17:00:00.000000')"+
            "INSERT INTO MENSAJES VALUES('jon@gmail.com', 'sansa@gmail.com', 'De hoy por la mañana', '2017-11-14 18:00:00.000000')"+
            "INSERT INTO MENSAJES VALUES('sansa@gmail.com', 'jon@gmail.com', 'No te creo', '2017-11-15 19:00:00.000000')";
}








